version: '3'
services:
  foundry:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ssh-volume:/root/.ssh
    command: tail -f /dev/null

volumes:
  ssh-volume: